canvasSize: 64     #Width of canvas; acceptable values: 32, 64, 128
artworkPrice: 350  #Price to purchase a map in vault $
claimTime: 60      #Minutes a player can claim a canvas for; 0 for unlimited use
cooldownTime: 1    #Minutes between when the map can be reset
maxMaps:           #max number of private artworks
  playerTier1: 3
  playerTier2: 5
  admin: 10