#ArtMap Config

#Currently supported languages: english only at the moment. Sorry!
language: english

#If true, prevents players from using obvious english swear words in artwork titles.
swearFilter: true