name: ${project.name}
main: me.Fupery.ArtMap.ArtMap
version: ${project.version}
description: ${project.description}
depends: []
author: Fupery

commands:
  artmap:
      usage:  |
        <command> save <title> : Save your artwork
        <command> delete <title> : Remove your artwork
        <command> preview <title> : Preview an artwork
        <command> list <playername|all> <pg> : Lists artworks
        <command> help : Display help
        <command> recipe <item> : Display recipe for artists/give recipe item to admin
        <command> backup : Create a backup of all current artworks
        <command> restore <backupname> <worldname> <-o> : Restore a backup folder from plugins/ArtMap/backups
permissions:
  artmap.artist:
    description: Allows creation of artworks
    default: op
  artmap.admin:
    description: Allows administrative commands
    children:
      artmap.artist: true
    default: op