name: ${project.name}
main: me.Fupery.ArtMap.ArtMap
version: ${project.version}
description: ${project.description}
depends: []
softdepend: [WorldGuard]
author: Fupery

commands:
  artmap:
      usage:  |
        <command> save <title> : Save your artwork
        <command> delete <title> : Remove your artwork
        <command> preview <title> : Preview an artwork
        <command> help : Display help
        <command> reload : Reloads the config
        <command> backup : Create a backup of all current artworks
        <command> restore <backupname> <worldname> <-o> : Restore a backup folder from plugins/ArtMap/backups
permissions:
  artmap.artist:
    description: Allows creation of artworks
    default: op
  artmap.artkit:
    description: Gives players a kit of art supplies while they use an easel
    default: op
  artmap.admin:
    description: Allows administrative commands
    children:
      artmap.artist: true
      artmap.artkit: true
    default: op