name: ${project.name}
main: me.Fupery.Artiste.Artiste
version: ${project.version}
description: ${project.description}
depends: [Vault]
author: Fupery

commands:
  artmap:
    usage: /artmap
    description: does stuff

permissions:
  artiste.artist:
    description: Lower tier players can only publish private artworks
    default: op
  artiste.admin:
    description: Allows administrative commands
    children:
      artiste.artist: true
    default: op