name: ${project.name}
main: me.Fupery.Artiste.Artiste
version: ${project.version}
description: ${project.description}
depends: [Vault]
author: Fupery

permissions:
  artiste.playerTier1:
    description: Lower tier players can only publish private artworks
    default: op
  artiste.playerTier2:
    description: Upper tier players can publish private and public artworks
    default: op
    children:
      artiste.playerTier1: true
  artiste.admin:
    description: Allows administrative commands
    children:
      artiste.playerTier1: true
      artiste.playerTier2: true
    default: op